{{- with .Values.dbProvidersSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rag-llm-frontend-external-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rag-llm-frontend-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
      {{- range .vault }}
        {{ printf "%s_%s" .key .field }}: {{ printf "{{ .%s_%s }}" .key .field  | quote }}
      {{- end }}
      {{- with .providers }}
        db_providers: {{ . | toJson | quote }}
      {{- end }}
  data:
  {{- range .vault }}
  - secretKey: {{ printf "%s_%s" .key .field }}
    remoteRef:
      key: {{ printf "secret/data/hub/%s" .key }}
      property: {{ .field }}
  {{- end }}
{{- end }}
