{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "rag-llm-frontend.fullname" . }}
  labels:
    {{- include "rag-llm-frontend.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/timeout: 5m
spec:
  host: {{ printf "%s.%s" (include "rag-llm-frontend.fullname" .) .Values.global.localClusterDomain }}
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: {{ include "rag-llm-frontend.fullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
